version: 0.0
os: linux 
files:
  - source: codedeploy
    destination: /var/lib/codedeploy-apps/HexBug
  - source: compose.yml
    destination: /var/lib/codedeploy-apps/HexBug
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: hooks/application-stop.sh
      timeout: 60
  ApplicationStart:
    - location: hooks/application-start.sh
      timeout: 300
